# Generated by Django 3.0.8 on 2020-07-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
